### ISSUE TITLE
ENV Variables seem to be borked

### ISSUE THREAD

**Issue by chrishough** [kejadlen/forecast.alfredworkflow#14]
```

[2016-09-28 16:52:30][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 400 Bad Request (OpenURI::HTTPError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
	from /Users/chrishough/Dropbox/ApplicationSync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.162ED98D-DE2C-4750-BCA4-29FCCA95592B/forecaster.rb:21:in `forecast'
	from /Users/chrishough/Dropbox/ApplicationSync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.162ED98D-DE2C-4750-BCA4-29FCCA95592B/forecaster.rb:8:in `forecast'
	from forecast.rb:60:in `<main>'```

**Comment by kejadlen** [comment]
Duplicate of #8?

**Comment by chrishough** [comment]
That worked.
