### ISSUE TITLE
400 Bad Request Error after configuring 

### ISSUE THREAD

**Issue by Alucardology** [kejadlen/forecast.alfredworkflow#8]
I encountered this error message after setting up both API keys. 

> [ERROR: alfred.workflow.input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 400 Bad Request (OpenURI::HTTPError)

**Comment by kejadlen** [comment]
Is there any more to that stacktrace than the Ruby error?

**Comment by jrturton** [comment]
I'm seeing the same error, the full trace is:

```
[2016-06-03 08:59:58][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 400 Bad Request (OpenURI::HTTPError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
	from /Users/richard/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.31F15205-1B1F-4D4D-8150-00A0E7EEBD74/forecaster.rb:21:in `forecast'
	from /Users/richard/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.31F15205-1B1F-4D4D-8150-00A0E7EEBD74/forecaster.rb:8:in `forecast'
	from forecast.rb:60:in `<main>'
```

**Comment by jrturton** [comment]
Which in turn seems to be the forecast API not being available. When I set the API key in debug mode I see this:

```
[2016-06-03 09:08:58][ERROR: action.script] /Users/richard/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.31F15205-1B1F-4D4D-8150-00A0E7EEBD74/vendor/bundle/ruby/2.0.0/gems/alphred-1.2.1/lib/alphred/config.rb:24:in `update!': uninitialized constant Alphred::Config::FileUtils (NameError)
	from -e:1:in `<main>'
```

**Comment by kejadlen** [comment]
Are you on the latest version of the workflow? This should've been fixed in 1.0.4. (https://github.com/kejadlen/alphred/issues/2)

**Comment by chanson** [comment]
I'm getting the same error, but looks like I'm on 1.0.3. Is 1.0.4 released? Looks like the download links on GitHub and Packal are for 1.0.3.

**Comment by jrturton** [comment]
Works for me now with 1.0.4 downloaded from 
https://github.com/kejadlen/forecast.alfredworkflow/releases
Probably the Packal link just needs updating, that's where I got it from.

**Comment by chanson** [comment]
that did it, thanks @jrturton

**Comment by kejadlen** [comment]
Oops - thanks, everyone! Updated the workflow on Packal.
