### ISSUE TITLE
Cannot start workflow

### ISSUE THREAD

**Issue by moookino** [kejadlen/forecast.alfredworkflow#9]
```

[ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from forecast.rb:2:in `<main>'
```

**Comment by kejadlen** [comment]
Released [v1.0.7](https://github.com/kejadlen/forecast.alfredworkflow/releases/tag/v1.0.7) which should hopefully fix this.
